<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Login') ?></h3>
            </div>
            <?php if (!empty($this->message)) { ?>
                <div class="alert alert-danger">
                    <?php echo $this->message; ?>
                </div>
            <?php } ?>
            <div class="panel-body">
                <?php echo $this->form()->openTag($this->form); ?>
                <?php echo $this->formCollection($this->form); ?>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
