<ul class="nav navbar-nav">
<?php
foreach ($this->container as $page) {
    $hasChildren = $page->hasPages();
    if (!$hasChildren) {
?>
        <li class="dropdown"><a href="<?php echo $page->getHref(); ?>"><?php echo $page->getLabel(); ?></a></li>
    <?php
    } else {
    ?>
        <li class="dropdown">
            <a href="<?php echo $page->getHref(); ?>" class="dropdown-toggle" data-toggle="dropdown">><?php echo $page->getLabel(); ?></a>
            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu">
            <?php
            foreach($page->getPages() as $child) {
            ?>
                <li><a href="<?php echo $child->getHref(); ?>"><?php echo $child->getLabel(); ?></a></li>
            <?php
            }
            ?>
            </ul>
        </li>
<?php
    }
}
?>
</ul>